### ISSUE TITLE
Does not recognize JSON-formatted request when other values present

### ISSUE THREAD

**Issue by oddevan** [Taproot/micropub-adapter#2]
When sending an update request from [Micropublish](https://micropublish.net), the application sets a `Content-type` header of `application\/json; charset=utf-8`. This causes the check on line 514 to fail, and the library attempts to parse nonexistent form data.

**Comment by oddevan** [comment]
I hope to have a PR for this soon; want to confirm my fixes first and then properly unit test it. :)

**Comment by barnabywalters** [comment]
Sounds good, let me know if you need any help with the PR, otherwise I look forward to reviewing and merging it :)
